name: tour
channels:
  - conda-forge
  - cyclus
  - defaults
dependencies:
  - python=3.9  
  - jupyterlab
  - dask
  - distributed
  - dask-labextension
  - pyspark=3.3.1
  - java-jdk
  - tqdm
  - python-graphviz
  - xgboost=1.6.2
  - pip:
    - ray[air]==2.0.1
    - xgboost_ray

